### PR TITLE
Feature: Throw errors with proper http code

### LINKED ISSUE #61: Server error handling for restful APIs
## **What’s the problem you're trying to solve**
We haven't had a proper way to handle errors for restful API, that is, we'll always throw "500 internal server error" for any errors.

## **Describe the solution you’d like**
Catch these errors and set the proper HTTP status code. We can wrap our errors when they occurred and set the desired HTTP code there.

## **Additional context**

### PR DESCRIPTION
**Pull request by oscar60310**
## Description
1. Custom errors
    I've created 4 errors for us:
    ```ts
    /** Expected errors, which is caused by users */
    export class UserError extends VulcanError {
      constructor(message?: string, options?: VulcanErrorOptions) {
        super(message, {
          ...options,
          httpCode: options?.httpCode || 400,
          code: options?.code || 'vulcan.userError',
          exitCode: options?.exitCode || 2,
        });
      }
    }
    
    /** Unexpected errors, which is caused by internal issues */
    export class InternalError extends VulcanError {
      constructor(message?: string, options?: VulcanErrorOptions) {
        super(message, {
          ...options,
          httpCode: options?.httpCode || 500,
          code: options?.code || 'vulcan.internalError',
          exitCode: options?.exitCode || 3,
        });
      }
    }
    
    /** The configurations e.g. vulcan.yaml, user.yaml ... are incorrect */
    export class ConfigurationError extends InternalError {
      constructor(message?: string, options?: VulcanErrorOptions) {
        super(message, {
          ...options,
          code: options?.code || 'vulcan.configError',
        });
      }
    }
    
    /** Error from template syntax */
    export class TemplateError extends InternalError {
      constructor(message?: string, options?: VulcanErrorOptions) {
        super(message, {
          ...options,
          code: options?.code || 'vulcan.templateError',
        });
      }
    }
    ```
2. Catch errors and set proper HTTP code and body.
3. Corrected the order of middlewares.

## Issue ticket number

closes #61

### CODE REVIEW

**Comment by kokokuo** [comment]
I discover one thing and would like to check does it was missed, The CLI init files `user.yaml` seems not to have `sample` in #86 [code href](https://github.com/Canner/vulcan-sql/pull/86/files#diff-dae705d89fb59e4513ec3d96f19f29bc5c20c67059fca22cb67d8307bd25b44bR9 )
Should it also need to add?

**Comment by oscar60310** [comment]
> I discover one thing and would like to check does it was missed, The CLI init files `user.yaml` seems not to have `sample` in #86 [code href](https://github.com/Canner/vulcan-sql/pull/86/files#diff-dae705d89fb59e4513ec3d96f19f29bc5c20c67059fca22cb67d8307bd25b44bR9) . Should it also need to add `sample` ?

Thanks for pointing out, that property is optional, builder won't send sample queries without setting it. So I think it's ok to leave it blank in init templates.

**Comment by kokokuo** [comment]
> > I discover one thing and would like to check does it was missed, The CLI init files `user.yaml` seems not to have `sample` in #86 [code href](https://github.com/Canner/vulcan-sql/pull/86/files#diff-dae705d89fb59e4513ec3d96f19f29bc5c20c67059fca22cb67d8307bd25b44bR9) . Should it also need to add `sample` ?
> 
> 
> 
> Thanks for pointing out, that property is optional, builder won't send sample queries without setting it. So I think it's ok to leave it blank in init templates.
> 
> 
> 
> 

If not set it, does the api spec still generated but not appear the response info in the api document?

**Comment by oscar60310** [comment]
> > > I discover one thing and would like to check does it was missed, The CLI init files `user.yaml` seems not to have `sample` in #86 [code href](https://github.com/Canner/vulcan-sql/pull/86/files#diff-dae705d89fb59e4513ec3d96f19f29bc5c20c67059fca22cb67d8307bd25b44bR9) . Should it also need to add `sample` ?
> > 
> > 
> > Thanks for pointing out, that property is optional, builder won't send sample queries without setting it. So I think it's ok to leave it blank in init templates.
> 
> If not set it, does the api spec still generated but not appear the response info in the api document? ( I would like to check for writing it to the our vulcansql document )

Yes, we'll get an empty response {} in the document.

**Comment by kokokuo** [comment]
> > > > I discover one thing and would like to check does it was missed, The CLI init files `user.yaml` seems not to have `sample` in #86 [code href](https://github.com/Canner/vulcan-sql/pull/86/files#diff-dae705d89fb59e4513ec3d96f19f29bc5c20c67059fca22cb67d8307bd25b44bR9) . Should it also need to add `sample` ?
> 
> > > 
> 
> > > 
> 
> > > Thanks for pointing out, that property is optional, builder won't send sample queries without setting it. So I think it's ok to leave it blank in init templates.
> 
> > 
> 
> > If not set it, does the api spec still generated but not appear the response info in the api document? ( I would like to check for writing it to the our vulcansql document )
> 
> 
> 
> Yes, we'll get an empty response {} in the document. 

Thank you!

**Review by kokokuo — APPROVED** [review]
LGTM 👍 👍 👍  
Thanks so much for helping me to develop the feature, really appreciated

**Pull request merged**
